server:
  port: 8080

spring:
  application:
    name: music-listen
  mail:
    host: smtp.qq.com
    port: 587
    username: 1796340674@qq.com
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    redis:
      host: 192.168.128.130
      port: 6379
      database: 0
      timeout: 3000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.128.130:3306/music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL到控制台
  global-config:
    db-config:
      logic-delete-field: delete_time
      logic-not-delete-value: 0
logging:
  level:
    com.yi.musiclisten.mapper: debug  # 你的mapper包路径
    com.baomidou.mybatisplus: debug
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: music
  secure: false




